let partyData=null,partyRecipe=null,partyGame=null;
function partyReturn(odds){if(!Number.isFinite(odds)||Math.abs(odds)<100)return null;const decimal=odds>0?1+odds/100:1+100/-odds;return {total:5*decimal,profit:5*(decimal-1),implied:100/decimal};}
function partyRender(){const el=document.getElementById('partyContent');if(!partyData)return;
 const now=Date.now(),games=partyData.games.filter(g=>Date.parse(g.kickoff)>now),stale=now-partyData.fetchedAt>5*60000;
 if(stale||!games.length){partyRecipe=null;document.getElementById('partyTicket').hidden=true;el.innerHTML='<p class="empty">'+(stale?'Refresh needed before using tonight’s ideas.':safe(partyData.note||'Tonight’s games have started. Pregame recipes are closed.'))+'</p>';return;}
 el.innerHTML='<p class="note">Tonight means Eastern time. Reference markets refreshed '+new Date(partyData.fetchedAt).toLocaleTimeString()+'. Choose one recipe for a $5 total ticket.</p>'+games.map(g=>'<h3>'+safe(g.name)+' · '+new Date(g.kickoff).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})+'</h3><p class="note">Moneyline/total reference: '+safe(g.source)+' via <a target="_blank" rel="noopener" href="'+safe(g.sourceUrl)+'">ESPN</a>. These are not combined sportsbook quotes.</p><div class="party-grid">'+(g.recipes.length?g.recipes.map(r=>'<article class="pick"><span class="badge">4-LEG LONG-SHOT IDEA · $5</span><h3>'+safe(r.title)+'</h3><ol>'+r.legs.map(l=>'<li>'+safe(l.text)+'<small>'+(l.verified?'Current reference market':'Prop idea · verify in your book')+'</small></li>').join('')+'</ol><p>'+safe(r.note)+'</p><button data-party-recipe="'+safe(r.id)+'">Use this recipe</button></article>').join(''):'<p>Not enough current market or player data for a recipe.</p>')+'</div>').join('');
}
async function partyRefresh(){try{const r=await fetch('/api/party-parlays',{cache:'no-store'});if(!r.ok)throw Error('Current game data is unavailable. No new party ticket generated.');partyData=await r.json();partyRecipe=null;document.getElementById('partyTicket').hidden=true;partyRender();}catch(e){document.getElementById('partyContent').textContent=e.message;}}
function partyQuote(){const out=document.getElementById('partyQuote'),raw=document.getElementById('partyOdds').value.trim(),quote=raw?partyReturn(Number(raw)):null;if(!quote){out.textContent='Enter the combined American odds shown by your sportsbook, e.g. +1800. No payout or hit probability is invented.';return;}out.textContent='$5 → $'+quote.total.toFixed(2)+' total return ($'+quote.profit.toFixed(2)+' profit). Price-implied break-even: '+quote.implied.toFixed(1)+'%, not a model forecast.';}
document.getElementById('partyToggle').addEventListener('click',()=>{const p=document.getElementById('partyPanel');p.hidden=!p.hidden;document.getElementById('partyToggle').setAttribute('aria-expanded',String(!p.hidden));if(!p.hidden){partyRefresh();p.scrollIntoView({behavior:'smooth'});}});
document.getElementById('partyRefresh').addEventListener('click',()=>{partyRecipe=null;document.getElementById('partyTicket').hidden=true;partyRefresh();});
document.addEventListener('click',e=>{const b=e.target.closest('[data-party-recipe]');if(!b||!partyData)return;for(const g of partyData.games){const r=g.recipes.find(r=>r.id===b.dataset.partyRecipe);if(r){if(Date.parse(g.kickoff)<=Date.now()||Date.now()-partyData.fetchedAt>5*60000){partyRender();return;}partyRecipe=r;partyGame=g;document.getElementById('partyTicket').hidden=false;document.getElementById('partySelected').textContent=g.name+' · '+r.title;document.getElementById('partyOdds').value='';partyQuote();document.getElementById('partyTicket').scrollIntoView({behavior:'smooth'});break;}}});
document.getElementById('partyOdds').addEventListener('input',partyQuote);
document.getElementById('partyCopy').addEventListener('click',async()=>{if(!partyRecipe||Date.parse(partyGame.kickoff)<=Date.now()||Date.now()-partyData.fetchedAt>5*60000){document.getElementById('partyQuote').textContent='Refresh the recipe first. Pregame copying closes at kickoff.';return;}const raw=document.getElementById('partyOdds').value.trim();if(raw&&!partyReturn(Number(raw))){document.getElementById('partyQuote').textContent='Enter valid American odds before copying, or leave the quote blank.';return;}const text='$5 PARTY PARLAY IDEA — '+partyGame.name+'\n'+partyRecipe.legs.map((l,i)=>(i+1)+'. '+l.text+(l.verified?'':' [confirm market + active status]')).join('\n')+'\n'+(raw?'User-entered combined odds: '+raw:'Combined odds: not quoted')+'\nEntertainment long shot; same-game legs are correlated. Review and place manually in your sportsbook.';try{await navigator.clipboard.writeText(text);document.getElementById('partyCopy').textContent='Copied recipe';}catch(e){document.getElementById('partyQuote').textContent=text;}});
setInterval(()=>{if(partyData&&!document.getElementById('partyPanel').hidden)partyRender();},60000);
