import assert from 'node:assert/strict';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {optimize,bracket,simulate}=require('../lib/campaign-model.js');const {events}=require('../api/season-scan.js');const P=require('../lib/season-push.cjs');
// A flex slot before RB must not steal the only legal RB. Every player is unique.
const p=[{id:'r',pos:'RB',weekly:20},{id:'w',pos:'WR',weekly:19}];const opt=optimize(p,['FLEX','RB']);assert.equal(opt.points,39);assert.deepEqual(opt.line.map(x=>x.id),['w','r']);assert.equal(optimize(p,['QB']),null);
for(const spots of [2,4,6,8]){const seeds=Array.from({length:spots},(_,i)=>i+1);for(const champion of seeds){const r=bracket(seeds,(a,b)=>a===champion||b===champion?champion:Math.min(a,b));assert.equal(r.winner,champion,'every seed can win '+spots);assert.ok(r.finalists.includes(champion));}}
const matches=[];bracket([1,2,3,4,5,6,7,8],(a,b,r)=>{matches.push([a,b,r]);return Math.min(a,b);});assert.deepEqual(matches.slice(0,4),[[1,8,0],[4,5,0],[2,7,0],[3,6,0]]);assert.deepEqual(matches.slice(4),[[1,4,1],[2,3,1],[1,2,2]]);
const teams=Array.from({length:12},(_,i)=>({id:i+1,name:'Team '+i,wins:0,ties:0,points:0,players:[{id:'p'+i,pos:'QB',weekly:20,outlook:20}]}));const data={week:1,lastWeek:1,spots:8,teams,slots:['QB'],schedule:{1:[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]]}};const sim=simulate(data,10000,44);assert.equal(sim.rows.reduce((n,r)=>n+r.title,0),100);assert.ok(Math.abs(sim.rows.reduce((n,r)=>n+r.make,0)-800)<.001);assert.ok(sim.rows.every(r=>r.title>6&&r.title<11));assert.deepEqual(simulate(data,10,2).rows,simulate(data,10,2).rows);
assert.throws(()=>simulate({...data,unsupported:'unsupported'},1),/unsupported/);
const fixture={week:1,teams:[{id:12,players:[{id:'p',injury:'Questionable'}]}],opportunities:[{id:'x',name:'Available Star',priority:'urgent',gain:6,drop:{name:'Bench'},bid:15}]};let doc={roster:12,seen:{},initialized:false};const first=events(fixture,doc);assert.equal(first.found.length,1);doc={...doc,...first,initialized:true};assert.equal(events(fixture,doc).found.length,0);fixture.teams[0].players[0].injury='Out';assert.equal(events(fixture,doc).found.length,1);fixture.opportunities[0].dropped={id:'newdrop'};assert.equal(events(fixture,doc).found.length,2);
process.env.SEASON_STORE_KEY='ab'.repeat(32);const encoded=P.encrypt({subscription:{endpoint:'secret-device'},seen:{}});assert.ok(!encoded.includes('secret-device'));assert.equal(P.decrypt(encoded).subscription.endpoint,'secret-device');assert.throws(()=>P.decrypt(encoded.slice(0,-4)+'AAAA'));assert.equal(P.validSubscription({endpoint:'https://127.0.0.1',keys:{}}),false);
console.log('Campaign optimizer, 2/4/6/8 brackets, probability conservation, alert deduplication, and encrypted subscriptions passed');
const {csv,summary}=require('../lib/usage.cjs');assert.deepEqual(csv('a,b\n"x,y","q""z"\n'),[{a:'x,y',b:'q"z'}]);assert.equal(summary([{week:1,targets:9,carries:3,receptions:5,receiving_yards:70}],2,{rec:1,rec_yd:.1}).points,12);assert.equal(summary([{week:2}],2,{}),null);
// Locked bench players cannot be promoted after kickoff; locked starters stay in their slot.
assert.equal(optimize([{id:'q1',pos:'QB',weekly:10,locked:true},{id:'q2',pos:'QB',weekly:30,locked:true}],['QB'],'weekly',['q1']).line[0].id,'q1');
assert.equal(optimize([{id:'q1',pos:'QB',weekly:10},{id:'q2',pos:'QB',weekly:30,locked:true}],['QB']).line[0].id,'q1');
const finished=structuredClone(data);finished.teams[0].current={final:true,points:100};finished.teams[1].current={final:true,points:1};const fsim=simulate(finished,100,3);assert.equal(fsim.rows.find(r=>r.id===1).wins,1);assert.equal(fsim.rows.find(r=>r.id===2).wins,0);
