/* Encrypted per-device documents in the existing Blob store. No subscription URL is public plaintext. */
const crypto=require('node:crypto');
const PREFIX='season-war-room/v1/';
function configured(){return !!(process.env.BLOB_READ_WRITE_TOKEN&&process.env.SEASON_STORE_KEY&&process.env.SEASON_VAPID_PUBLIC&&process.env.SEASON_VAPID_PRIVATE&&process.env.SEASON_SCAN_KEY);}
function encrypt(value){const iv=crypto.randomBytes(12),key=Buffer.from(process.env.SEASON_STORE_KEY,'hex');const cipher=crypto.createCipheriv('aes-256-gcm',key,iv);const body=Buffer.concat([cipher.update(JSON.stringify(value),'utf8'),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64');}
function decrypt(value){const b=Buffer.from(value,'base64'),cipher=crypto.createDecipheriv('aes-256-gcm',Buffer.from(process.env.SEASON_STORE_KEY,'hex'),b.subarray(0,12));cipher.setAuthTag(b.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(b.subarray(28)),cipher.final()]).toString());}
function idOf(sub){return crypto.createHash('sha256').update(sub.endpoint).digest('hex');}
function validSubscription(sub){try{const u=new URL(sub.endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&(/^(fcm\.googleapis\.com|updates\.push\.services\.mozilla\.com|web\.push\.apple\.com)$/.test(u.hostname)||u.hostname.endsWith('.notify.windows.com'))&&/^[A-Za-z0-9_-]{80,100}$/.test(sub.keys?.p256dh||'')&&/^[A-Za-z0-9_-]{20,30}$/.test(sub.keys?.auth||'');}catch(e){return false;}}
async function save(doc){const {put}=require('@vercel/blob');return put(PREFIX+idOf(doc.subscription)+'.txt',encrypt(doc),{access:'public',addRandomSuffix:false,allowOverwrite:true,contentType:'text/plain',cacheControlMaxAge:60});}
async function documents(){const {list}=require('@vercel/blob');const docs=[];let cursor;do{const page=await list({prefix:PREFIX,limit:100,cursor});for(const b of page.blobs){const r=await fetch(b.url+'?v='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Subscription store unavailable');docs.push({url:b.url,doc:decrypt(await r.text())});}cursor=page.hasMore?page.cursor:null;}while(cursor);return docs;}
async function remove(sub){const {del}=require('@vercel/blob');await del(PREFIX+idOf(sub)+'.txt');}
async function send(sub,payload){const push=require('web-push');push.setVapidDetails('https://draft-war-room-chi.vercel.app',process.env.SEASON_VAPID_PUBLIC,process.env.SEASON_VAPID_PRIVATE);try{await push.sendNotification(sub,JSON.stringify(payload),{TTL:1800,timeout:12000,urgency:'high'});return true;}catch(e){if([404,410].includes(e.statusCode)){await remove(sub);return false;}throw e;}}
async function body(req){if(req.body&&typeof req.body==='object')return req.body;let s='';for await(const part of req){s+=part;if(s.length>8000)throw Error('Request too large');}return JSON.parse(s||'{}');}
async function health(write){const {put,list}=require('@vercel/blob'),path='season-war-room/health.json';if(write)return put(path,JSON.stringify(write),{access:'public',addRandomSuffix:false,allowOverwrite:true,contentType:'application/json',cacheControlMaxAge:60});const page=await list({prefix:path,limit:1});if(!page.blobs.length)return null;const r=await fetch(page.blobs[0].url+'?v='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(12000)});return r.ok?r.json():null;}
module.exports={health,configured,encrypt,decrypt,idOf,validSubscription,save,documents,remove,send,body};
