const crypto=require('node:crypto');const P=require('../lib/season-push.cjs');const {build}=require('../lib/campaign-service.cjs');
function events(data,doc){const found=[],seen={...(doc.seen||{})},injuries={};
 for(const p of data.opportunities){if(p.priority!=='urgent'&&!(p.dropped&&p.priority==='watch'))continue;const id=p.id+':'+(p.dropped?.id||data.week)+':'+p.priority;if(!seen[id])found.push({id,title:(p.dropped?'League drop: ':'Waiver upgrade: ')+p.name,body:'+'+p.gain.toFixed(1)+' projected starter points. Consider '+p.drop.name+'; FAAB estimate $'+p.bid+'. Review before submitting in Sleeper.'});seen[id]=Date.now();}
 const mine=data.teams.find(t=>t.id===doc.roster);for(const p of mine?.players||[]){injuries[p.id]=p.injury||'Healthy';if(doc.initialized&&doc.injuries?.[p.id]!==injuries[p.id]&&doc.injuries?.[p.id]!=null){const id='injury:'+p.id+':'+injuries[p.id]+':'+data.week;if(!seen[id])found.push({id,title:'Roster update: '+p.name,body:injuries[p.id]+'. Check your lineup and backups in Sleeper.'});seen[id]=Date.now();}}
 return {found,seen:Object.fromEntries(Object.entries(seen).filter(([,t])=>Date.now()-t<35*86400000)),injuries};}
module.exports=async(req,res)=>{res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');const reply=(s,b)=>{res.statusCode=s;res.end(JSON.stringify(b));};
 const expected=process.env.SEASON_SCAN_KEY||'',actual=(req.headers.authorization||'').replace(/^Bearer /,'');if(!expected||Buffer.byteLength(expected)!==Buffer.byteLength(actual)||!crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(actual)))return reply(401,{error:'Unauthorized'});
 if(!['GET','POST'].includes(req.method))return reply(405,{error:'Use POST'});if(!P.configured())return reply(503,{error:'Alerts not configured'});
 try{let sent=0;const docs=await P.documents();for(const {doc}of docs){const data=await build(doc.league,doc.roster);const e=events(data,doc);let alive=true;const payloads=e.found.length>4?[{id:'season-summary-'+data.week,title:e.found.length+' league updates',body:e.found.slice(0,3).map(p=>p.title).join(' · ')+'. Open your waiver radar for details.'}]:e.found;for(const p of payloads){alive=await P.send(doc.subscription,{title:p.title,body:p.body,tag:p.id});if(!alive)break;sent++;}if(alive)await P.save({...doc,seen:e.seen,injuries:e.injuries,initialized:true,lastScanAt:Date.now()});}
 const checkedAt=new Date().toISOString();await P.health({checkedAt,ok:true});return reply(200,{ok:true,devices:docs.length,sent,checkedAt});}catch(e){return reply(502,{error:'Scan failed; scheduler will retry. No subscription details are exposed.'});}
};module.exports.events=events;
